import {
  Activity,
  Archive,
  Database,
  HardDrive,
  ShieldCheck,
} from "lucide-react";
import {
  type RecordingRegroupResult,
  type UploadSourceRepairResult,
} from "./types";

export const uiCopy = {
  zh: {
    appName: "7GRecorder 管理后台",
    title: "录播控制台",
    navLabel: "管理分区",
    nav: {
      overview: "总览",
      profiles: "录制配置",
      recordings: "录像文件",
      uploads: "上传设置",
      songs: "歌曲识别",
      jobs: "任务",
      accounts: "账号管理",
      system: "系统设置",
    },
    songsTitle: "歌曲识别与切分",
    songsSettings: "识别设置",
    songsEnabled: "启用歌曲识别",
    acrCredential: "ACRCloud 凭证",
    acrCredentialName: "凭证名称",
    acrSecret: "Access Token JSON",
    saveAcrCredential: "保存 ACRCloud 凭证",
    providerRegion: "ACRCloud 区域",
    providerContainer: "File Scanning Container ID",
    destinationCosProfile: "音频目标 COS 配置 ID",
    songsPrefix: "音频对象前缀",
    boundaryPadding: "边界扩展（毫秒）",
    saveSongsSettings: "保存识别设置",
    songsSettingsFailed: "保存识别设置失败，请检查凭证和 COS 配置。",
    songsCredentialFailed: "保存 ACRCloud 凭证失败。",
    analysisSource: "选择 COS 视频",
    startAnalysis: "开始识别",
    startAnalysisFailed: "无法创建识别任务，请确认模块已启用且来源仍可用。",
    noSongSources: "暂无可分析的 COS 视频。",
    analysisRuns: "识别任务",
    analysisCreated: "创建时间",
    noAnalysisRuns: "暂无识别任务。",
    recognizedSongs: "识别结果",
    songTimeRange: "时间范围",
    songAudio: "音频",
    noRecognizedSongs: "暂无识别结果。",
    statusRows: [
      { label: "录制核心", value: "配置已就绪", icon: Activity },
      { label: "SQLite", value: "部署时自动迁移", icon: Database },
      { label: "本地存储", value: "始终启用", icon: HardDrive },
      { label: "可选模块", value: "配置后启用", icon: Archive },
      { label: "部署", value: "仅 main 分支发布生产", icon: ShieldCheck },
    ],
    language: "语言",
    chinese: "中文",
    english: "English",
    myAccount: "我的账号",
    signOut: "退出登录",
    signIn: "登录",
    session: "会话",
    username: "用户名",
    password: "密码",
    role: "角色",
    status: "状态",
    enabled: "启用",
    disabled: "停用",
    allowed: "允许",
    blocked: "禁止",
    access: "权限",
    systemSettings: "系统设置",
    siteTLS: "站点域名与 HTTPS",
    siteTLSHint:
      "腾讯云负责续期；7GRecorder 校验证书后交由宿主机 Nginx 安全部署。",
    primaryDomain: "主域名",
    additionalDomains: "附加域名",
    additionalDomainsHint: "每行一个域名。DNS 记录需已指向生产服务器。",
    tlsCredential: "腾讯云 SSL 凭证",
    tlsCredentialLabel: "凭证名称",
    tlsCredentialSecret: "Secret JSON",
    createTLSCredential: "保存 SSL 凭证",
    saveSiteTLS: "保存并排队同步",
    syncSiteTLS: "立即同步",
    siteTLSStatus: "同步状态",
    latestCertificate: "云端证书",
    stagedCertificate: "待部署证书",
    deployedCertificate: "已部署证书",
    certificateExpires: "证书到期",
    lastChecked: "最近检查",
    siteTLSSaveFailed: "站点 TLS 保存失败，请检查域名和凭证。",
    tlsCredentialCreateFailed: "SSL 凭证保存失败，请检查 Secret JSON。",
    profiles: "录制配置",
    allOwners: "全部账号",
    policyUnavailable: "账号权限暂不可用。",
    loginFailed: "登录失败，请检查用户名和密码。",
    newProfile: "新建配置",
    editProfile: "编辑配置",
    archivedProfile: "已归档配置",
    owner: "所属账号",
    currentOwner: "当前所属账号",
    name: "名称",
    roomId: "直播间 ID",
    streamer: "主播",
    streamerUid: "主播 UID",
    timezone: "时区",
    publicSlug: "公开地址",
    quality: "画质",
    segmentSeconds: "分段秒数",
    finalizeGraceSeconds: "收尾宽限秒数",
    autoRecord: "自动录制",
    recordDanmaku: "录制弹幕",
    publicPage: "公开页面",
    save: "保存",
    create: "创建",
    cancel: "取消",
    close: "关闭",
    restoreProfile: "恢复配置",
    archiveProfile: "归档配置",
    confirmArchive: "确认归档",
    profileSaveFailed: "配置保存失败，请检查直播间是否重复以及必填项。",
    recordingProfiles: "录制配置",
    total: (count: number) => `共 ${count} 条`,
    new: "新建",
    ownerColumn: "所属账号",
    room: "直播间",
    runtime: "运行",
    sync: "同步",
    actions: "操作",
    edit: "编辑",
    archived: "已归档",
    noProfiles: "暂无录制配置。",
    newManager: "新建管理员",
    initialPassword: "初始密码",
    accountCreationFailed: "账号创建失败，请检查用户名和密码。",
    accounts: "账号",
    account: "账号",
    noAccounts: "暂无账号。",
    editAccount: "编辑账号",
    accountSaveFailed: "账号保存失败，请检查用户名、密码或账号状态。",
    newPassword: "新密码",
    newPasswordHint: "留空表示不修改密码。",
    saveAccount: "保存账号",
    currentAccount: "当前账号",
    noAction: "无可用操作",
    disable: "停用",
    enable: "启用",
    editProfiles: "编辑录制配置",
    bilibiliConfig: "Bilibili 配置",
    cosConfig: "COS 配置",
    neteaseConfig: "网易云配置",
    localFiles: "本地文件",
    localStorage: "本地存储",
    checkingStorage: "正在检查存储。",
    indexedVideos: "已索引视频",
    indexedSize: "已索引大小",
    liveAnalyticsSize: "直播分析原文",
    managedSize: "托管总占用",
 derivedSize: "打包与剪辑文件",
 songsSize: "歌曲文件",
    diskAvailable: "磁盘可用",
    protected: "已保护",
    health: "健康状态",
    needReclaim: "需回收",
    previewReclaimable: "预估可回收",
    diskSummary: (
      used: number,
      total: string,
      completed: number,
      configured: boolean,
    ) =>
      `磁盘已用 ${used}%，总计 ${total}。已完成录像 ${completed} 条。设置：${configured ? "已配置" : "使用默认值"}。`,
    storageSettings: "存储设置",
    maxRecordingGB: "录像上限 GB",
    minFreeGB: "最低空闲 GB",
    emergencyFreeGB: "紧急保留 GB",
    cleanupTargetPercent: "清理目标 %",
    storageSaveFailed: "存储设置保存失败，请检查阈值。",
    cleanupPreview: "清理预览",
    oldestUnprotected: "最早的未保护已完成录像",
    recording: "录像",
    profile: "配置",
    closed: "结束时间",
    files: "文件数",
    reclaimable: "可回收",
    untitled: "未命名",
    noCleanupCandidates: "暂无可清理候选。",
    runCleanup: "执行清理",
    cleanupConfirm:
      "将删除最旧的未保护已完成录像文件，并保留数据库记录。确认执行？",
    cleanupResult: (
      recordings: number,
      files: number,
      bytes: string,
      skipped: number,
    ) =>
      `清理完成：删除 ${recordings} 条录像、${files} 个文件，回收 ${bytes}，跳过 ${skipped} 条。`,
    cleanupFailed: "清理失败，请查看服务器日志。",
    jobs: "任务",
    job: "任务",
    jobType: "类型",
    jobSyncRecorderProfile: "同步录制配置",
    jobMergeUploadSource: "合并可上传视频",
    jobPackageUploadSource: "封装可上传视频",
    jobApplyUploadSourceEdit: "应用剪辑",
    jobUploadBilibili: "上传到 Bilibili",
    jobUploadCOS: "上传到 COS",
    jobUploadCOSRecordingFile: "上传原始文件到 COS",
    jobSyncSiteTLS: "同步站点 TLS 证书",
    jobStatusPending: "待开始",
    jobStatusRunning: "运行中",
    jobStatusSucceeded: "已成功",
    jobStatusFailed: "失败",
    jobStatusCancelled: "已取消",
    resourceClass: "资源",
    runAfter: "计划时间",
    attempts: "尝试",
    lastError: "最近错误",
    retry: "重试",
    retryJob: "重试任务",
    confirmAmbiguousBilibiliRetry:
      "上次 Bilibili 上传被中断，平台可能已经收到稿件。请先在创作中心确认同标题、同日期稿件不存在。确认不存在并继续重试吗？",
    cancelJob: "取消任务",
    jobsFailed: "任务加载失败，请查看服务器日志。",
    noJobs: "暂无任务。",
    recordings: "录像文件",
    scan: "扫描",
    regroupToday: "重整最新日期",
    regroupTodayConfirm:
      "将按当前列表最新录像的录制日期和 10 分钟连续窗口重整已生成的可上传视频。不会删除本地文件或 COS 对象；存在 Bilibili 投稿或运行中任务的分组会被跳过。确认继续？",
    regroupResult: (result: RecordingRegroupResult) => {
      const totals = result.items.reduce(
        (sum, item) => ({
          replaced: sum.replaced + item.replaced_sources,
          created: sum.created + item.created_sources,
          cancelled: sum.cancelled + item.cancelled_jobs,
          blocked: sum.blocked + (item.blocked?.length ?? 0),
        }),
        { replaced: 0, created: 0, cancelled: 0, blocked: 0 },
      );
      return `重整 ${result.china_date}：替换旧父视频 ${totals.replaced}，生成新父视频 ${totals.created}，取消旧任务 ${totals.cancelled}，阻止 ${totals.blocked} 组。`;
    },
    regroupFailed: "重整失败，请查看服务器日志。",
    repairUploadSources: "修复上传源",
    repairUploadSourcesConfirm:
      "将检查上传源产物是否仍在本地磁盘，缺失时自动回退到合并或封装步骤并取消下游上传任务。确认继续？",
    repairUploadSourcesResult: (result: UploadSourceRepairResult) =>
      `修复：检查 ${result.checked} 个，回退合并 ${result.reset_to_merge} 个，回退封装 ${result.reset_to_package} 个，重置 merge/package 任务 ${result.merge_jobs_reset + result.package_jobs_reset} 个，取消上传任务 ${result.upload_jobs_cancelled} 个，原始文件缺失阻止 ${result.source_missing_blocks} 个。`,
    repairUploadSourcesFailed: "修复失败，请查看服务器日志。",
    refresh: "刷新",
    scanResult: (imported: number, updated: number, skipped: number) =>
      `扫描：新增 ${imported}，更新 ${updated}，忽略 ${skipped}。`,
    scanFailed: "扫描失败，请查看服务器日志。",
    startTime: "录制时间",
    completedAt: "完成时间",
    duration: "时长",
    size: "大小",
    sourceSize: "源大小",
    uploadedSize: "上传大小",
    compressionStatus: "COS 文件",
    path: "路径",
    fileStatus: "文件状态",
    noFile: "无文件",
    unprotect: "取消保护",
    protect: "保护",
    download: "下载",
    downloadFromCos: "COS 下载",
    downloadLocal: "本地下载",
    openBilibili: "打开 Bilibili",
    details: "详情",
    recordingDetails: "录像详情",
    uploadSources: "可上传视频",
    uploadSourceDiscoverResult: (
      created: number,
      ignored: number,
      mergeJobsEnqueued: number,
      packageJobsEnqueued: number,
    ) =>
      `生成可上传视频：新增 ${created}，等待 ${ignored}，补建合并任务 ${mergeJobsEnqueued}，补建封装任务 ${packageJobsEnqueued}。`,
    uploadSourcePendingMerge: "待合并",
    uploadSourceMerging: "合并中",
    uploadSourceMergeCompleteRefreshing: "合并完成，刷新中",
    uploadSourcePendingPackage: "待封装",
    uploadSourcePackaging: "封装中",
    uploadSourcePackageCompleteRefreshing: "封装完成，刷新中",
    uploadSourceReady: "可上传",
    uploadSourceUploading: "上传中",
    uploadSourceUploadFailed: "上传失败",
    uploadSourceComplete: "上传完成",
    uploadSourceLocalCleaned: "本地文件已自动清理",
    uploadSourceActiveRecording: "录制中",
    uploadSourceMergeFailed: "合并失败",
    uploadSourcePackageFailed: "封装失败",
    uploadSourceWaitingReview: "等待审核",
    requireReview: "需要审核",
    rerequireReview: "重新审核",
    approveReview: "审核完成",
    reviewRequired: "需审核",
    reviewPending: "审核中",
    editCuts: "删除区间",
    editCutsPlaceholder: "00:10:00-00:12:30\n01:05:20-01:06:00",
    applyEdit: "应用剪辑",
    editQueued: "剪辑任务已排队",
    editFailed: "剪辑提交失败，请查看服务器日志。",
    bilibiliStatus: "Bilibili",
    cosStatus: "COS",
    uploadStatusDisabled: "未启用",
    uploadStatusWaitingSource: "等待文件",
    uploadStatusPending: "待上传",
    uploadStatusUploading: "上传中",
    uploadStatusAvailable: "已上传",
    uploadStatusVerified: "已发布",
    uploadStatusFailed: "失败",
    compressionStatusDisabled: "原文件",
    compressionStatusPending: "待压缩",
    compressionStatusCompressing: "压缩中",
    compressionStatusCompressed: "已压缩",
    compressionStatusSkippedLowGain: "收益低跳过",
    compressionStatusFailed: "压缩失败",
    sourceSegments: "原始片段",
    sourceOutputs: "发布分片",
    danmakuFiles: "原始弹幕",
    downloadDanmakuFromCos: "下载弹幕",
    showSourceSegments: "显示原始片段",
    hideSourceSegments: "隐藏原始片段",
    timeline: "合并时间轴",
    recordingStatus: "录像状态",
    localStorageStatus: "本地状态",
    file: "文件",
    fileKind: "文件类型",
    fileSize: "文件大小",
    filePath: "文件路径",
    visibleSize: "当前列表大小",
    shortSegments: "短片段",
    protectedRecordings: "受保护录像",
    loadingRecordings: "正在加载录像。",
    noRecordings: "暂无已索引录像。",
    api: "API",
    release: "版本",
    checking: "检查中",
    unknown: "未知",
    chinaTime: "中国时间",
    search: "搜索",
    searchPlaceholder: "搜索名称、直播间、路径",
    sortBy: "排序",
    sortNewest: "录制时间：新到旧",
    sortOldest: "录制时间：旧到新",
    sortDuration: "时长：长到短",
    sortSize: "大小：大到小",
    sortName: "名称：A 到 Z",
    sortRoom: "直播间：小到大",
    sortUsername: "用户名：A 到 Z",
    sortRole: "角色：A 到 Z",
    sortUpdated: "更新时间：新到旧",
    sortRunAfter: "计划时间：近到远",
    sortStatus: "状态：A 到 Z",
    uploadSettings: "上传设置",
    uploadProfile: "录制配置",
    uploadProfileHint: "Bilibili 和 COS 配置按录制配置分别保存。",
    credentialVault: "凭证库",
    newCredential: "新建凭证",
    platform: "平台",
    purpose: "用途",
    accountLabel: "账号标识",
    externalUid: "外部 UID",
    credentialSecret: "凭证 JSON",
    credentialSecretHint: "只会加密保存；保存后不会再显示明文。",
    createCredential: "保存凭证",
    credentialCreateFailed: "凭证保存失败，请检查 JSON 和必填项。",
    noCredentials: "暂无凭证。",
    bilibiliPublishing: "Bilibili 投稿",
    cosStorage: "腾讯云 COS",
    credential: "凭证",
    noCredentialSelected: "未选择凭证",
    moduleEnabled: "启用模块",
    moduleDisabled: "模块未启用",
    bilibiliTitleTemplate: "视频标题模板",
    bilibiliDescriptionTemplate: "视频简介模板",
    bilibiliTags: "标签",
    bilibiliCopyright: "版权类型",
    bilibiliCopyrightOriginal: "自制",
    bilibiliCopyrightRepost: "转载",
    bilibiliSource: "转载来源",
    bilibiliUploadLimit: "Bilibili 上传并发",
    bilibiliTemplateHint:
      "可用变量：{{profile_name}}、{{streamer_name}}、{{room_id}}、{{date}}、{{date_compact}}、{{start_time}}、{{end_time}}、{{started_at_china}}、{{completed_at_china}}、{{live_ordinal}}、{{part_count}}。",
    cosRegion: "COS 地域",
    cosBucket: "COS Bucket",
    cosPrefix: "COS 前缀",
    cosMaxManagedGB: "COS 托管上限 GB",
    saveBilibiliConfig: "保存 Bilibili 配置",
    saveCosConfig: "保存 COS 配置",
    uploadConfigSaveFailed:
      "上传配置保存失败，请检查凭证、区域、Bucket 或 JSON。",
    reconcileUploadJobs: "生成上传任务",
    reconcileUploadHint: "只会为可上传视频补建缺失的 Bilibili/COS 任务。",
    uploadReconcileResult: (
      publications: number,
      bilibiliJobs: number,
      cosObjects: number,
      cosJobs: number,
      cosFileObjects: number,
      cosFileJobs: number,
    ) =>
      `上传任务：Bilibili 发布 ${publications}，Bilibili 任务 ${bilibiliJobs}，COS 视频对象 ${cosObjects}，COS 视频任务 ${cosJobs}，COS 原始文件 ${cosFileObjects}，原始文件任务 ${cosFileJobs}。`,
    uploadReconcileFailed: "上传任务生成失败，请查看服务器日志。",
    uploadAccessBlocked: "当前账号没有上传模块配置权限。",
    emptyFiltered: "没有匹配结果。",
  },
  en: {
    appName: "7GRecorder Admin",
    title: "Recorder Console",
    navLabel: "Admin sections",
    nav: {
      overview: "Overview",
      profiles: "Profiles",
      recordings: "Recordings",
      uploads: "Upload Settings",
      songs: "Song Recognition",
      jobs: "Jobs",
      accounts: "Accounts",
      system: "System Settings",
    },
    songsTitle: "Song Recognition and Clips",
    songsSettings: "Recognition Settings",
    songsEnabled: "Enable song recognition",
    acrCredential: "ACRCloud Credential",
    acrCredentialName: "Credential Name",
    acrSecret: "Access Token JSON",
    saveAcrCredential: "Save ACRCloud Credential",
    providerRegion: "ACRCloud Region",
    providerContainer: "File Scanning Container ID",
    destinationCosProfile: "Audio Destination COS Profile ID",
    songsPrefix: "Audio Object Prefix",
    boundaryPadding: "Boundary Padding (ms)",
    saveSongsSettings: "Save Recognition Settings",
    songsSettingsFailed:
      "Could not save recognition settings. Check the credential and COS profile.",
    songsCredentialFailed: "Could not save the ACRCloud credential.",
    analysisSource: "Select COS Video",
    startAnalysis: "Start Recognition",
    startAnalysisFailed:
      "Could not create the analysis job. Check settings and source availability.",
    noSongSources: "No COS videos are available for analysis.",
    analysisRuns: "Recognition Jobs",
    analysisCreated: "Created",
    noAnalysisRuns: "No recognition jobs yet.",
    recognizedSongs: "Recognized Songs",
    songTimeRange: "Time Range",
    songAudio: "Audio",
    noRecognizedSongs: "No recognized songs yet.",
    statusRows: [
      { label: "Recording Core", value: "Profiles ready", icon: Activity },
      { label: "SQLite", value: "Migrated on deploy", icon: Database },
      { label: "Local Storage", value: "Always enabled", icon: HardDrive },
      {
        label: "Optional Modules",
        value: "Disabled until configured",
        icon: Archive,
      },
      { label: "Deployment", value: "main-only production", icon: ShieldCheck },
    ],
    language: "Language",
    chinese: "中文",
    english: "English",
    myAccount: "My Account",
    signOut: "Sign out",
    signIn: "Sign in",
    session: "Session",
    username: "Username",
    password: "Password",
    role: "Role",
    status: "Status",
    enabled: "ENABLED",
    disabled: "DISABLED",
    allowed: "Allowed",
    blocked: "Blocked",
    access: "Access",
    systemSettings: "System Settings",
    siteTLS: "Site Domain & HTTPS",
    siteTLSHint:
      "Tencent Cloud renews the certificate; 7GRecorder validates it before host Nginx deploys it.",
    primaryDomain: "Primary Domain",
    additionalDomains: "Additional Domains",
    additionalDomainsHint:
      "One domain per line. DNS must already point to the production server.",
    tlsCredential: "Tencent SSL Credential",
    tlsCredentialLabel: "Credential Name",
    tlsCredentialSecret: "Secret JSON",
    createTLSCredential: "Save SSL Credential",
    saveSiteTLS: "Save & Queue Sync",
    syncSiteTLS: "Sync Now",
    siteTLSStatus: "Sync Status",
    latestCertificate: "Cloud Certificate",
    stagedCertificate: "Staged Certificate",
    deployedCertificate: "Deployed Certificate",
    certificateExpires: "Certificate Expiry",
    lastChecked: "Last Checked",
    siteTLSSaveFailed:
      "Could not save Site TLS. Check the domains and credential.",
    tlsCredentialCreateFailed:
      "Could not save the SSL credential. Check the secret JSON.",
    profiles: "Profiles",
    allOwners: "All owners",
    policyUnavailable: "Access policy is not available.",
    loginFailed: "Login failed. Check the credentials.",
    newProfile: "New Profile",
    editProfile: "Edit Profile",
    archivedProfile: "Archived profile",
    owner: "Owner",
    currentOwner: "Current owner",
    name: "Name",
    roomId: "Room ID",
    streamer: "Streamer",
    streamerUid: "Streamer UID",
    timezone: "Timezone",
    publicSlug: "Public Slug",
    quality: "Quality",
    segmentSeconds: "Segment Seconds",
    finalizeGraceSeconds: "Finalize Grace Seconds",
    autoRecord: "Auto Record",
    recordDanmaku: "Record Danmaku",
    publicPage: "Public Page",
    save: "Save",
    create: "Create",
    cancel: "Cancel",
    close: "Close",
    restoreProfile: "Restore profile",
    archiveProfile: "Archive profile",
    confirmArchive: "Confirm archive",
    profileSaveFailed:
      "Profile save failed. Check unique room and required fields.",
    recordingProfiles: "Recording Profiles",
    total: (count: number) => `${count} total`,
    new: "New",
    ownerColumn: "Owner",
    room: "Room",
    runtime: "Runtime",
    sync: "Sync",
    actions: "Actions",
    edit: "Edit",
    archived: "Archived",
    noProfiles: "No profiles yet.",
    newManager: "New Manager",
    initialPassword: "Initial Password",
    accountCreationFailed:
      "Account creation failed. Check username and password.",
    accounts: "Accounts",
    account: "Account",
    noAccounts: "No accounts yet.",
    editAccount: "Edit Account",
    accountSaveFailed:
      "Account save failed. Check username, password, or account status.",
    newPassword: "New Password",
    newPasswordHint: "Leave blank to keep the current password.",
    saveAccount: "Save Account",
    currentAccount: "Current account",
    noAction: "No actions",
    disable: "Disable",
    enable: "Enable",
    editProfiles: "Edit profiles",
    bilibiliConfig: "Bilibili config",
    cosConfig: "COS config",
    neteaseConfig: "NetEase config",
    localFiles: "Local files",
    localStorage: "Local Storage",
    checkingStorage: "Checking storage.",
    indexedVideos: "Indexed Videos",
    indexedSize: "Indexed Size",
    liveAnalyticsSize: "Live Analytics Raw",
    managedSize: "Managed Usage",
 derivedSize: "Packaged and edited files",
 songsSize: "Song files",
    diskAvailable: "Disk Available",
    protected: "Protected",
    health: "Health",
    needReclaim: "Need Reclaim",
    previewReclaimable: "Preview Reclaimable",
    diskSummary: (
      used: number,
      total: string,
      completed: number,
      configured: boolean,
    ) =>
      `Disk used: ${used}% of ${total}. Completed recordings: ${completed}. Settings: ${
        configured ? "configured" : "derived default"
      }.`,
    storageSettings: "Storage Settings",
    maxRecordingGB: "Max Recording GB",
    minFreeGB: "Min Free GB",
    emergencyFreeGB: "Emergency Free GB",
    cleanupTargetPercent: "Cleanup Target %",
    storageSaveFailed: "Storage settings save failed. Check the thresholds.",
    cleanupPreview: "Cleanup Preview",
    oldestUnprotected: "Oldest unprotected completed recordings",
    recording: "Recording",
    profile: "Profile",
    closed: "Closed",
    files: "Files",
    reclaimable: "Reclaimable",
    untitled: "Untitled",
    noCleanupCandidates: "No cleanup candidates.",
    runCleanup: "Run Cleanup",
    cleanupConfirm:
      "This will delete the oldest unprotected completed local recording files while keeping database records. Continue?",
    cleanupResult: (
      recordings: number,
      files: number,
      bytes: string,
      skipped: number,
    ) =>
      `Cleanup finished: deleted ${recordings} recordings, ${files} files, reclaimed ${bytes}, skipped ${skipped}.`,
    cleanupFailed: "Cleanup failed. Check server logs.",
    jobs: "Jobs",
    job: "Job",
    jobType: "Type",
    jobSyncRecorderProfile: "Sync recording profile",
    jobMergeUploadSource: "Merge upload source",
    jobPackageUploadSource: "Package upload source",
    jobApplyUploadSourceEdit: "Apply edit",
    jobUploadBilibili: "Upload to Bilibili",
    jobUploadCOS: "Upload to COS",
    jobUploadCOSRecordingFile: "Upload raw file to COS",
    jobSyncSiteTLS: "Sync site TLS certificate",
    jobStatusPending: "Pending",
    jobStatusRunning: "Running",
    jobStatusSucceeded: "Succeeded",
    jobStatusFailed: "Failed",
    jobStatusCancelled: "Cancelled",
    resourceClass: "Resource",
    runAfter: "Run After",
    attempts: "Attempts",
    lastError: "Last Error",
    retry: "Retry",
    retryJob: "Retry job",
    confirmAmbiguousBilibiliRetry:
      "The previous Bilibili upload was interrupted and may already exist. First verify that no matching title/date is present in Creator Center. Confirm it is absent and retry?",
    cancelJob: "Cancel job",
    jobsFailed: "Jobs failed to load. Check server logs.",
    noJobs: "No jobs yet.",
    recordings: "Recordings",
    scan: "Scan",
    regroupToday: "Regroup Latest Date",
    regroupTodayConfirm:
      "Regroup existing upload sources for the newest recording date in the current list using the 10-minute continuity window. This will not delete local files or COS objects; groups with Bilibili publications or running jobs will be skipped. Continue?",
    regroupResult: (result: RecordingRegroupResult) => {
      const totals = result.items.reduce(
        (sum, item) => ({
          replaced: sum.replaced + item.replaced_sources,
          created: sum.created + item.created_sources,
          cancelled: sum.cancelled + item.cancelled_jobs,
          blocked: sum.blocked + (item.blocked?.length ?? 0),
        }),
        { replaced: 0, created: 0, cancelled: 0, blocked: 0 },
      );
      return `Regrouped ${result.china_date}: ${totals.replaced} old sources replaced, ${totals.created} new sources created, ${totals.cancelled} old jobs cancelled, ${totals.blocked} groups blocked.`;
    },
    regroupFailed: "Regroup failed. Check server logs.",
    repairUploadSources: "Repair Sources",
    repairUploadSourcesConfirm:
      "Check upload-source files on disk. Missing derived files will roll back to merge or package and downstream upload jobs will be cancelled. Continue?",
    repairUploadSourcesResult: (result: UploadSourceRepairResult) =>
      `Repair: checked ${result.checked}, reset ${result.reset_to_merge} to merge and ${result.reset_to_package} to package, reset ${result.merge_jobs_reset + result.package_jobs_reset} merge/package jobs, cancelled ${result.upload_jobs_cancelled} upload jobs, blocked ${result.source_missing_blocks} sources with missing raw files.`,
    repairUploadSourcesFailed: "Repair failed. Check server logs.",
    refresh: "Refresh",
    scanResult: (
      imported: number,
      updated: number,
      skipped: number,
      errors?: number,
      lastError?: string,
    ) =>
      `Scan: ${imported} imported, ${updated} updated, ${skipped} ignored${errors ? `, ${errors} errors (last: ${lastError || "unknown"})` : ""}.`,
    scanFailed: "Scan failed. Check server logs.",
    startTime: "Recording Time",
    completedAt: "Completed",
    duration: "Duration",
    size: "Size",
    sourceSize: "Source Size",
    uploadedSize: "Uploaded Size",
    compressionStatus: "COS file",
    path: "Path",
    fileStatus: "File Status",
    noFile: "NO_FILE",
    unprotect: "Unprotect",
    protect: "Protect",
    download: "Download",
    downloadFromCos: "COS Download",
    downloadLocal: "Local Download",
    openBilibili: "Open Bilibili",
    details: "Details",
    recordingDetails: "Recording Details",
    uploadSources: "Upload Sources",
    uploadSourceDiscoverResult: (
      created: number,
      ignored: number,
      mergeJobsEnqueued: number,
      packageJobsEnqueued: number,
    ) =>
      `Upload sources: ${created} created, ${ignored} waiting, ${mergeJobsEnqueued} merge jobs and ${packageJobsEnqueued} package jobs backfilled.`,
    uploadSourcePendingMerge: "Pending merge",
    uploadSourceMerging: "Merging",
    uploadSourceMergeCompleteRefreshing: "Merge finished, refreshing",
    uploadSourcePendingPackage: "Pending package",
    uploadSourcePackaging: "Packaging",
    uploadSourcePackageCompleteRefreshing: "Package finished, refreshing",
    uploadSourceReady: "Ready to upload",
    uploadSourceUploading: "Uploading",
    uploadSourceUploadFailed: "Upload failed",
    uploadSourceComplete: "Upload complete",
    uploadSourceLocalCleaned: "Local files automatically cleaned",
    uploadSourceActiveRecording: "Recording",
    uploadSourceMergeFailed: "Merge failed",
    uploadSourcePackageFailed: "Package failed",
    uploadSourceWaitingReview: "Waiting review",
    requireReview: "Require review",
    rerequireReview: "Re-review",
    approveReview: "Approve",
    reviewRequired: "Needs review",
    reviewPending: "In review",
    editCuts: "Cut ranges",
    editCutsPlaceholder: "00:10:00-00:12:30\n01:05:20-01:06:00",
    applyEdit: "Apply edit",
    editQueued: "Edit job queued",
    editFailed: "Failed to submit edit. Check server logs.",
    bilibiliStatus: "Bilibili",
    cosStatus: "COS",
    uploadStatusDisabled: "Disabled",
    uploadStatusWaitingSource: "Waiting for source",
    uploadStatusPending: "Pending upload",
    uploadStatusUploading: "Uploading",
    uploadStatusAvailable: "Uploaded",
    uploadStatusVerified: "Published",
    uploadStatusFailed: "Failed",
    compressionStatusDisabled: "Original",
    compressionStatusPending: "Pending",
    compressionStatusCompressing: "Compressing",
    compressionStatusCompressed: "Compressed",
    compressionStatusSkippedLowGain: "Skipped",
    compressionStatusFailed: "Failed",
    sourceSegments: "Original Segments",
    sourceOutputs: "Publish Parts",
    danmakuFiles: "Raw Danmaku",
    downloadDanmakuFromCos: "Download Danmaku",
    showSourceSegments: "Show Original Segments",
    hideSourceSegments: "Hide Original Segments",
    timeline: "Timeline",
    recordingStatus: "Recording Status",
    localStorageStatus: "Local Status",
    file: "File",
    fileKind: "File Type",
    fileSize: "File Size",
    filePath: "File Path",
    visibleSize: "Visible Size",
    shortSegments: "Short Segments",
    protectedRecordings: "Protected Recordings",
    loadingRecordings: "Loading recordings.",
    noRecordings: "No recordings indexed yet.",
    api: "API",
    release: "Release",
    checking: "checking",
    unknown: "unknown",
    chinaTime: "China Time",
    search: "Search",
    searchPlaceholder: "Search name, room, or path",
    sortBy: "Sort by",
    sortNewest: "Recording time: newest",
    sortOldest: "Recording time: oldest",
    sortDuration: "Duration: longest",
    sortSize: "Size: largest",
    sortName: "Name: A to Z",
    sortRoom: "Room: low to high",
    sortUsername: "Username: A to Z",
    sortRole: "Role: A to Z",
    sortUpdated: "Updated: newest",
    sortRunAfter: "Run after: soonest",
    sortStatus: "Status: A to Z",
    uploadSettings: "Upload Settings",
    uploadProfile: "Recording Profile",
    uploadProfileHint:
      "Bilibili and COS settings are saved per recording profile.",
    credentialVault: "Credential Vault",
    newCredential: "New Credential",
    platform: "Platform",
    purpose: "Purpose",
    accountLabel: "Account Label",
    externalUid: "External UID",
    credentialSecret: "Credential JSON",
    credentialSecretHint:
      "Stored encrypted only; plaintext is never shown after saving.",
    createCredential: "Save Credential",
    credentialCreateFailed:
      "Credential save failed. Check JSON and required fields.",
    noCredentials: "No credentials yet.",
    bilibiliPublishing: "Bilibili Publishing",
    cosStorage: "Tencent COS",
    credential: "Credential",
    noCredentialSelected: "No credential selected",
    moduleEnabled: "Module enabled",
    moduleDisabled: "Module disabled",
    bilibiliTitleTemplate: "Video Title Template",
    bilibiliDescriptionTemplate: "Video Description Template",
    bilibiliTags: "Tags",
    bilibiliCopyright: "Copyright",
    bilibiliCopyrightOriginal: "Original",
    bilibiliCopyrightRepost: "Repost",
    bilibiliSource: "Repost Source",
    bilibiliUploadLimit: "Bilibili Upload Concurrency",
    bilibiliTemplateHint:
      "Variables: {{profile_name}}, {{streamer_name}}, {{room_id}}, {{date}}, {{date_compact}}, {{start_time}}, {{end_time}}, {{started_at_china}}, {{completed_at_china}}, {{live_ordinal}}, {{part_count}}.",
    cosRegion: "COS Region",
    cosBucket: "COS Bucket",
    cosPrefix: "COS Prefix",
    cosMaxManagedGB: "COS Managed Limit GB",
    saveBilibiliConfig: "Save Bilibili Config",
    saveCosConfig: "Save COS Config",
    uploadConfigSaveFailed:
      "Upload config save failed. Check credential, region, bucket, or JSON.",
    reconcileUploadJobs: "Create Upload Jobs",
    reconcileUploadHint:
      "Backfills missing Bilibili/COS jobs for ready upload sources only.",
    uploadReconcileResult: (
      publications: number,
      bilibiliJobs: number,
      cosObjects: number,
      cosJobs: number,
      cosFileObjects: number,
      cosFileJobs: number,
    ) =>
      `Upload jobs: ${publications} Bilibili publications, ${bilibiliJobs} Bilibili jobs, ${cosObjects} COS video objects, ${cosJobs} COS video jobs, ${cosFileObjects} COS raw files, ${cosFileJobs} raw file jobs.`,
    uploadReconcileFailed:
      "Upload job reconciliation failed. Check server logs.",
    uploadAccessBlocked: "This account cannot configure upload modules.",
    emptyFiltered: "No matching results.",
  },
} as const;
