export const copy = {
  zh: {
    title: "任务中心",
    subtitle: "查看后台任务的执行进度，处理需要关注的任务。",
    refresh: "刷新",
    search: "搜索任务",
    sort: "排序",
    updated: "最近更新",
    scheduled: "计划时间",
    statusSort: "任务状态",
    all: "当前列表",
    running: "执行中",
    failed: "需要关注",
    success: "已完成",
    job: "任务",
    profile: "录制配置",
    status: "状态",
    attempts: "尝试次数",
    schedule: "计划执行 · 中国时间",
    error: "最近错误",
    actions: "操作",
    retry: "重试",
    cancel: "取消",
    noAction: "—",
    loading: "正在加载任务…",
    empty: "暂无任务",
    noMatch: "没有匹配的任务",
    emptyHelp: "后台任务创建后会出现在这里。",
    failedLoad: "任务加载失败",
    retryLoad: "重新加载",
    actionFailed: "操作失败，请检查任务状态后重试。",
    actionDone: "操作已提交",
    limit: "展示最近最多 100 条任务；搜索和统计仅针对当前列表。",
    confirm:
      "此 B站投稿的结果不确定。请先在创作中心确认尚未产生相同投稿，再确认重试。",
    progress: "进度",
    states: {
      PENDING: "等待执行",
      RUNNING: "执行中",
      SUCCEEDED: "已完成",
      FAILED: "失败",
      CANCELLED: "已取消",
    },
    types: {
      UPLOAD_BILIBILI: "B站投稿",
      VERIFY_BILIBILI: "投稿核验",
      UPLOAD_COS_OBJECT: "COS 上传",
      MERGE_UPLOAD_SOURCE: "视频合并",
      APPLY_UPLOAD_SOURCE_EDIT: "视频编辑",
    },
  },
  en: {
    title: "Job center",
    subtitle: "Follow background work and resolve tasks that need attention.",
    refresh: "Refresh",
    search: "Search jobs",
    sort: "Sort",
    updated: "Recently updated",
    scheduled: "Scheduled time",
    statusSort: "Status",
    all: "In this list",
    running: "Running",
    failed: "Needs attention",
    success: "Completed",
    job: "Job",
    profile: "Profile",
    status: "Status",
    attempts: "Attempts",
    schedule: "Scheduled · China time",
    error: "Last error",
    actions: "Actions",
    retry: "Retry",
    cancel: "Cancel",
    noAction: "—",
    loading: "Loading jobs…",
    empty: "No jobs yet",
    noMatch: "No matching jobs",
    emptyHelp: "Background tasks will appear here when created.",
    failedLoad: "Unable to load jobs",
    retryLoad: "Try again",
    actionFailed: "Action failed. Check the task and try again.",
    actionDone: "Action submitted",
    limit:
      "Latest 100 jobs at most. Search and statistics cover this list only.",
    confirm:
      "This Bilibili submission has an uncertain outcome. Check Creator Center and confirm no matching submission exists before retrying.",
    progress: "Progress",
    states: {
      PENDING: "Pending",
      RUNNING: "Running",
      SUCCEEDED: "Completed",
      FAILED: "Failed",
      CANCELLED: "Cancelled",
    },
    types: {
      UPLOAD_BILIBILI: "Bilibili upload",
      VERIFY_BILIBILI: "Verify publication",
      UPLOAD_COS_OBJECT: "COS upload",
      MERGE_UPLOAD_SOURCE: "Merge video",
      APPLY_UPLOAD_SOURCE_EDIT: "Edit video",
    },
  },
};
