// Command frontend-contracts emits HTTP JSON resource shapes, never database schema.
package main

import (
	"fmt"
	"github.com/7grecorder/7grecorder/backend/internal/account"
	"github.com/7grecorder/7grecorder/backend/internal/job"
	"github.com/7grecorder/7grecorder/backend/internal/liveanalytics"
	"github.com/7grecorder/7grecorder/backend/internal/profile"
	"github.com/7grecorder/7grecorder/backend/internal/recording"
	"github.com/7grecorder/7grecorder/backend/internal/sitetls"
	"github.com/7grecorder/7grecorder/backend/internal/songs"
	"github.com/7grecorder/7grecorder/backend/internal/upload"
	"reflect"
	"strings"
)

func shape(t reflect.Type) string {
	if t.PkgPath() == "encoding/json" && t.Name() == "RawMessage" {
		return "unknown"
	}
	switch t.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int64, reflect.Int32, reflect.Float64:
		return "number"
	case reflect.Interface:
		return "unknown"
	case reflect.Pointer:
		return shape(t.Elem()) + " | null"
	case reflect.Slice:
		return "Array<" + shape(t.Elem()) + "> | null"
	case reflect.Map:
		return "Record<string, " + shape(t.Elem()) + "> | null"
	case reflect.Struct:
		return "{\n" + fields(t) + "}"
	default:
		panic("unsupported contract type: " + t.String())
	}
}
func fields(t reflect.Type) string {
	var out strings.Builder
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if f.Anonymous {
			out.WriteString(fields(f.Type))
			continue
		}
		tag := strings.Split(f.Tag.Get("json"), ",")
		if tag[0] == "-" {
			continue
		}
		if tag[0] == "" {
			panic("missing JSON tag: " + f.Name)
		}
		optional := ""
		if len(tag) > 1 && tag[1] == "omitempty" {
			optional = "?"
		}
		fmt.Fprintf(&out, "  %s%s: %s;\n", tag[0], optional, shape(f.Type))
	}
	return out.String()
}
func main() {
	fmt.Println("// Generated by backend/cmd/frontend-contracts. Do not edit.")
	resources := []struct {
		name  string
		value any
	}{
		{"User", account.User{}}, {"ManagerPolicy", account.ManagerPolicy{}}, {"Account", account.Account{}},
		{"Job", job.Job{}}, {"RetryRequest", job.RetryRequest{}},
		{"RecordingSettings", profile.RecordingSettings{}}, {"RecordingProfile", profile.RecordingProfile{}},
		{"Recording", recording.Recording{}}, {"RecordingFile", recording.File{}}, {"UploadSourceItem", recording.UploadSource{}},
		{"UploadSourceSegment", recording.UploadSourceSegment{}}, {"UploadSourceOutput", recording.UploadSourceOutput{}},
		{"LocalStorageStatus", recording.LocalStorageStatus{}}, {"LocalStorageSettings", recording.LocalStorageSettings{}},
		{"CleanupCandidate", recording.CleanupCandidate{}}, {"CleanupRunResult", recording.CleanupRunResult{}},
		{"Credential", upload.Credential{}}, {"BilibiliPublishingConfig", upload.PublishingConfig{}}, {"COSStorageConfig", upload.COSConfig{}},
		{"SiteTLSSettings", sitetls.Settings{}}, {"SongSettings", songs.Settings{}}, {"SongAnalysisSource", songs.AnalysisSource{}},
		{"SongAnalysisRun", songs.AnalysisRun{}}, {"RecognizedSong", songs.Song{}},
		{"LiveAnalyticsConfig", liveanalytics.Config{}}, {"LiveCaptureSession", liveanalytics.Session{}},
	}
	for _, resource := range resources {
		fmt.Printf("export type %s = %s;\n", resource.name, shape(reflect.TypeOf(resource.value)))
	}
}
